### ISSUE TITLE
Linux & MAC installation instructions

### ISSUE THREAD

**Issue by thijsvdc** [lgastevens/ACLI-terminal#1]
Hi Ludovico,

The installation instructions for both Linux and MAC still contain the links to oranda.fr, and it seems that the zip files are no longer available over there. I can't find them on this github repo either.

Thanks
Thijs

**Comment by thijsvdc** [comment]
Same for the Windows .exe

**Comment by lgastevens** [comment]
Hi, thanks for feedback.
You can find those files under the Releases for the repository.
Here's the direct link: [https://github.com/lgastevens/ACLI-terminal/releases](url)
![image](https://github.com/lgastevens/ACLI-terminal/assets/10697590/c0a3b920-e263-44d6-a538-35ba527daa83)
Best regards
Ludovico

**Comment by thijsvdc** [comment]
Well it seems that I completely missed that... Thanks Ludovico!
